# Generated by Django 3.2.3 on 2021-05-25 14:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Proyecto', '0002_requerimiento'),
    ]

    operations = [
        migrations.CreateModel(
            name='Analisis_Requerimientos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_campo', models.CharField(max_length=30)),
                ('tipo', models.CharField(max_length=30)),
                ('descripcion', models.TextField()),
                ('requerimiento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Proyecto.requerimiento')),
            ],
        ),
    ]
