# Generated by Django 3.2.3 on 2021-05-25 14:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Proyecto', '0003_analisis_requerimientos'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='analisis_requerimientos',
            options={'verbose_name_plural': 'E3 Analisis de requerimientos'},
        ),
        migrations.AddField(
            model_name='analisis_requerimientos',
            name='nombre_tabla',
            field=models.CharField(default='NOMBRE DEL OBJETO', max_length=30),
        ),
    ]
