# Generated by Django 3.2.3 on 2021-05-27 17:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Proyecto', '0004_auto_20210525_1440'),
    ]

    operations = [
        migrations.AddField(
            model_name='requerimiento',
            name='prioridad',
            field=models.CharField(default='SIN PRIORIDAD', max_length=30),
        ),
        migrations.AlterField(
            model_name='analisis_requerimientos',
            name='tipo',
            field=models.CharField(choices=[('BooleanField', 'BooleanField'), ('CharField', 'CharField'), ('DateField', 'DateField'), ('DateTimeField', 'DateTimeField'), ('DecimalField', 'DecimalField'), ('EmailField', 'EmailField'), ('FileField', 'FileField'), ('ImageField', 'ImageField'), ('IntegerField', 'IntegerField'), (' GenericIPAddressField', ' GenericIPAddressField'), ('MultipleChoiceField', 'MultipleChoiceField'), ('TypedMultipleChoiceField', 'TypedMultipleChoiceField'), ('NullBooleanField', 'NullBooleanField'), ('RegexField', 'RegexField'), ('SlugField', 'SlugField'), ('TimeField', 'TimeField'), ('URLField', 'URLField'), ('UUIDField', 'UUIDField'), ('ComboField', 'ComboField'), ('MultiValueField', 'MultiValueField'), ('SplitDateTimeField', 'SplitDateTimeField'), ('ModelMultipleChoiceField', 'ModelMultipleChoiceField'), ('ModelChoiceField', 'ModelChoiceField'), ('TextField', 'TextField')], max_length=30),
        ),
    ]
