# Generated by Django 3.2.3 on 2021-05-27 20:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Proyecto', '0005_auto_20210527_1205'),
    ]

    operations = [
        migrations.CreateModel(
            name='Priorizacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_inicio', models.DateField()),
                ('fecha_fin', models.DateField()),
                ('className', models.CharField(max_length=30)),
                ('requerimiento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Proyecto.requerimiento')),
            ],
        ),
    ]
