# Generated by Django 3.2.3 on 2021-05-28 14:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Proyecto', '0006_priorizacion'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='priorizacion',
            options={'verbose_name_plural': 'E4 Priorización de actividades'},
        ),
        migrations.CreateModel(
            name='DiagramaProcesos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('diagrama', models.TextField()),
                ('proyecto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Proyecto.proyecto')),
            ],
        ),
    ]
