# Generated by Django 3.2.3 on 2021-05-28 20:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Proyecto', '0008_auto_20210528_1150'),
    ]

    operations = [
        migrations.AddField(
            model_name='priorizacion',
            name='dias',
            field=models.IntegerField(default=1),
        ),
    ]
