# Generated by Django 3.2.3 on 2021-05-28 21:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Proyecto', '0009_priorizacion_dias'),
    ]

    operations = [
        migrations.CreateModel(
            name='ApartadosAplicacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50)),
            ],
            options={
                'verbose_name_plural': 'E1.1 Apartados del Proyecto',
            },
        ),
    ]
