# Generated by Django 3.2.3 on 2021-05-28 22:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Proyecto', '0011_apartadosaplicacion_proyecto'),
    ]

    operations = [
        migrations.AddField(
            model_name='requerimiento',
            name='apartado',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Proyecto.apartadosaplicacion'),
        ),
    ]
